### ISSUE TITLE
os path problem with mac user

### ISSUE THREAD

**Issue by JackHuyn** [JackHuyn/SWE_4103_Gr3#9]
can we update to os path to this:

  # Get the directory where the current script is located
  script_directory = os.path.dirname(os.path.abspath(__file__))
  # Get the full path to the file
  file_name = "swe4103-7b261-firebase-adminsdk.json"
  file_path = os.path.join(script_directory, file_name)
  cred = credentials.Certificate(file_path)
  firebase_admin.initialize_app(cred)

since the change saquib did is only for window os, it gave error for mac/linux user ( i assume)

**Comment by JBBamba** [comment]
Hey Jack, which file are you referring to?

**Comment by JackHuyn** [comment]
It should be at the start of backend.py

**Comment by brennanleblanc0** [comment]
I think I accidentally fixed this in one of my commits so...
